name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses5

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Setup Android SDK
        run: |
          mkdir -p ~/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"

          echo "$HOME/android-sdk/build-tools/34.0.0:$PATH" >> $GITHUB_ENV

          # Verify aidl installation
          ls -la ~/android-sdk/build-tools/34.0.0/aidl
          ~/android-sdk/build-tools/34.0.0/aidl --version || echo "AIDL check failed"

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app
          path: bin/*.apk
