name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip

    - name: Set up Android SDK environment
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

    - name: Get Date
      id: get-date
      run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache .buildozer folder
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython

    - name: Clean and update Buildozer
      run: |
        buildozer android clean
        buildozer android update

    - name: Build APK with Buildozer
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk
