name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-8-jdk

      - name: Install Buildozer
        run: pip install buildozer

      - name: Setup Android SDK and build tools
        run: |
          mkdir -p ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          
          export ANDROID_SDK_ROOT=~/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
          
          # Verify aidl is installed
          ls -la $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl
          $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl --version

      - name: Build with Buildozer
        run: |
          export ANDROID_SDK_ROOT=~/android-sdk
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: kivy-app
          path: bin/*.apk
