name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip git zip unzip \
            openjdk-17-jdk \
            zlib1g-dev libffi-dev libssl-dev libsqlite3-dev \
            autoconf automake libtool pkg-config cmake make patch \
            ninja-build gettext libfreetype6-dev

      - name: Setup Android SDK
        run: |
          mkdir -p ~/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

          mkdir -p ~/android-sdk/licenses
          echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/android-sdk/licenses/android-sdk-license
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > ~/android-sdk/licenses/android-sdk-preview-license

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" "platforms;android-33" \
            "build-tools;34.0.0" "ndk;25.2.9519653" "cmake;3.22.1"

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          buildozer android clean

      - name: Build APK
        run: |
          echo "[app]
title = MyApp
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy,pillow
orientation = portrait

[buildozer]
log_level = 2
android.accept_sdk_license = True
android.sdk_path = $HOME/android-sdk
android.ndk_path = $HOME/android-sdk/ndk/25.2.9519653
android.api = 33
android.minapi = 21" > buildozer.spec

          buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
          retention-days: 1
