name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential autoconf automake libtool pkg-config zlib1g-dev libssl-dev libncurses-dev openjdk-17-jdk unzip git

    - name: Upgrade pip and install buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Initialize buildozer if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Cache .buildozer directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
