name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer

    - name: Cache buildozer directories
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          .buildozer_global
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Setup Android SDK
      run: |
        # Create Android SDK directory
        mkdir -p ${HOME}/android-sdk

        # Download and extract command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d ${HOME}/android-sdk/cmdline-tools
        mv ${HOME}/android-sdk/cmdline-tools/cmdline-tools ${HOME}/android-sdk/cmdline-tools/latest

        # Set environment variables
        echo "ANDROID_SDK_ROOT=${HOME}/android-sdk" >> $GITHUB_ENV
        echo "${HOME}/android-sdk/cmdline-tools/latest/bin:${HOME}/android-sdk/platform-tools:${HOME}/android-sdk/build-tools/34.0.0:${PATH}" >> $GITHUB_ENV

        # Accept licenses
        yes | ${HOME}/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install required components
        ${HOME}/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"

        # Verify installation
        ls -la ${HOME}/android-sdk/build-tools/34.0.0/
        ${HOME}/android-sdk/build-tools/34.0.0/aidl --version

    - name: Configure Buildozer environment
      run: |
        # Create expected directory structure
        mkdir -p ~/.buildozer/android/platform/android-sdk
        ln -s ${HOME}/android-sdk ~/.buildozer/android/platform/android-sdk

        # Set environment variables for Buildozer
        echo "export ANDROID_SDK_ROOT=${HOME}/android-sdk" >> ~/.bashrc
        echo "export ANDROID_NDK_HOME=${HOME}/android-sdk/ndk/25.2.9519653" >> ~/.bashrc
        echo "export PATH=${HOME}/android-sdk/cmdline-tools/latest/bin:${HOME}/android-sdk/platform-tools:${HOME}/android-sdk/build-tools/34.0.0:${PATH}" >> ~/.bashrc

    - name: Build APK
      run: |
        source ~/.bashrc
        buildozer -v android debug

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
