name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libncurses6 \
          zlib1g-dev \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Build APK with debug
      run: |
        # Initialize if no spec file exists
        if [ ! -f buildozer.spec ]; then
          buildozer init
          sed -i "s/^#requirements = .*/requirements = kivy/" buildozer.spec
        fi
        
        # Clean previous builds
        buildozer android clean
        
        # Build with full debug output
        buildozer -v android debug 2>&1 | tee build.log
        
        # Verify build success
        if grep -q "Build failed" build.log; then
          echo "Build failed! Last errors:"
          tail -n 50 build.log | grep -i error
          exit 1
        fi

    - name: Find and prepare APK
      run: |
        # Create bin directory if it doesn't exist
        mkdir -p bin
        
        # Search for APK in common locations
        APK_PATH=$(find . -name "*.apk" | head -1)
        
        if [ -z "$APK_PATH" ]; then
          echo "APK not found! Searching all directories:"
          find . -type f -name "*.apk"
          echo "Build log contents:"
          cat build.log
          exit 1
        fi
        
        echo "Found APK at: $APK_PATH"
        cp "$APK_PATH" bin/
        echo "APK copied to bin directory"
        ls -la bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
