name: Kivy App to APK

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64

      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "Using Python==$(python --version)"
        shell: bash

      - name: Install and upgrade dependencies
        run: |
          sudo apt update
          sudo apt install -y git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses6 \
            libncursesw6 \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev
          export PATH=$PATH:~/.local/bin/
          python3 -m pip install --upgrade \
            Cython==0.29.33 \
            buildozer
        shell: bash

      - name: Install requirements in requirements.txt if it exists
        run: |
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi
        shell: bash

      # First run to initialize Buildozer and download SDK/NDK
      - name: Initialize Buildozer (SDK/NDK install)
        run: |
          source venv/bin/activate
          buildozer android debug || true
        shell: bash

      - name: Find sdkmanager path
        id: find_sdkmanager
        run: |
          SDKMANAGER_PATH=$(find $HOME/.buildozer/android/platform/android-sdk/ -type f -name sdkmanager | head -n 1)
          if [ -z "$SDKMANAGER_PATH" ]; then
            echo "sdkmanager not found!"
            exit 1
          fi
          echo "SDKMANAGER_PATH=$SDKMANAGER_PATH" >> $GITHUB_ENV
          echo "Found sdkmanager at $SDKMANAGER_PATH"

      - name: Accept Android SDK licenses
        run: |
          yes | "$SDKMANAGER_PATH" --licenses || true
        shell: bash

      - name: Install Android Build Tools 36
        run: |
          "$SDKMANAGER_PATH" "build-tools;36.0.0"
        shell: bash

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug
        shell: bash

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
