name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install --no-cache-dir cython==0.29.36 buildozer

      - name: Setup Android environment
        run: |
          # Create Android SDK directory
          mkdir -p ~/android-sdk

          # Download command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest

          # Set environment variables
          echo "ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=~/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=~/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

          # Accept licenses
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

          # Install Android components
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

          # Update PATH
          echo "PATH=~/android-sdk/platform-tools:~/android-sdk/build-tools/34.0.0:$PATH" >> $GITHUB_ENV

          # Verify installation
          ~/android-sdk/build-tools/34.0.0/aidl --version || echo "AIDL verification failed"

      - name: Configure Buildozer
        run: |
          # Create expected directory structure
          mkdir -p ~/.buildozer/android/platform
          ln -sfn ~/android-sdk ~/.buildozer/android/platform/android-sdk
          ln -sfn ~/android-sdk/ndk/25.2.9519653 ~/.buildozer/android/platform/android-ndk-r25b

          # Initialize Buildozer
          buildozer init || true
          cat buildozer.spec

      - name: Build APK (with detailed logging)
        run: |
          set -x  # Enable debug output
          echo "Python path: $(which python)"
          echo "Buildozer path: $(which buildozer)"
          echo "Android SDK path: $ANDROID_SDK_ROOT"
          echo "Current PATH: $PATH"
          
          # Run build with verbose output
          buildozer -v android debug 2>&1 | tee build.log
          
          # Check build result
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== BUILD FAILED ==="
            echo "Last 50 lines of log:"
            tail -n 50 build.log
            echo "Checking for APK files:"
            ls -la bin/ || true
            exit 1
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
