name: Build Kivy APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          python3-setuptools \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev

    - name: Install Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android SDK components
      run: |
        sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        sdkmanager --install "ndk;21.4.7075529"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install kivy

    - name: Create buildozer.spec if it doesn't exist
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Configure buildozer.spec
      run: |
        # Update buildozer.spec with required settings
        sed -i 's/android.ndk_path = .*/android.ndk_path = \/usr\/local\/lib\/android\/sdk\/ndk\/21.4.7075529/' buildozer.spec
        sed -i 's/android.sdk_path = .*/android.sdk_path = \/usr\/local\/lib\/android\/sdk/' buildozer.spec
        sed -i 's/android.accept_sdk_license = .*/android.accept_sdk_license = True/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-debug
        path: bin/*.apk

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Google Play (optional)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      # Uncomment and configure if you want to auto-upload to Google Play
      # You'll need to set up GOOGLE_PLAY_SERVICE_ACCOUNT_JSON secret
      # uses: r0adkll/upload-google-play@v1
      # with:
      #   serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      #   packageName: com.yourcompany.yourapp
      #   releaseFiles: bin/*.apk
      #   track: internal
      run: echo "Skipping Google Play upload. Configure the commented section above to enable."
