name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Setup Android SDK
      run: |
        # Create Android SDK directory
        mkdir -p ~/android-sdk

        # Download and extract command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest

        # Set environment variables
        echo "ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=~/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "PATH=~/android-sdk/cmdline-tools/latest/bin:~/android-sdk/platform-tools:~/android-sdk/build-tools/34.0.0:$PATH" >> $GITHUB_ENV

        # Accept licenses
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

        # Install required components
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0" \
          "ndk;25.2.9519653"

        # Verify installation
        ls -la ~/android-sdk/build-tools/34.0.0/
        ~/android-sdk/build-tools/34.0.0/aidl --version || echo "AIDL verification failed"

    - name: Configure Buildozer
      run: |
        # Create expected directory structure
        mkdir -p ~/.buildozer/android/platform
        ln -sf ~/android-sdk ~/.buildozer/android/platform/android-sdk

        # Verify symlink
        ls -la ~/.buildozer/android/platform/

    - name: Build APK with Buildozer
      run: |
        # Print environment for debugging
        env | sort

        # Verify tools are available
        which aidl
        which aapt
        which zipalign

        # Run buildozer with debug output
        buildozer -v android debug 2>&1 | tee build.log

        # Print build log if failed
        if [ $? -ne 0 ]; then
          echo "Build failed. Log:"
          cat build.log
          exit 1
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk

    - name: Upload build log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
