name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel \
          build-essential git zip unzip openjdk-17-jdk

        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK & NDK requirements
      run: |
        buildozer android clean
        buildozer android update

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
