name: Build Kivy APK
on:
  push:
    branches: [main]

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            make \
            patch \
            ninja-build \
            gettext \
            libfreetype6-dev

      - name: Clean up existing Android tools
        run: |
          sudo rm -rf /usr/local/lib/android/sdk/ndk/*

      - name: Setup Android SDK
        run: |
          mkdir -p ~/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest

          mkdir -p ~/android-sdk/tools/bin
          ln -s ~/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/android-sdk/tools/bin/sdkmanager

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

          mkdir -p ~/android-sdk/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/android-sdk/licenses/android-sdk-preview-license

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

      - name: Install Buildozer
        run: |
          python -m pip install --user --upgrade pip wheel
          python -m pip install --user buildozer==1.5.0 cython==0.29.36
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

          cat << 'EOF' > buildozer.spec
[app]
title = MyApp
package.name = myapp
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy,pillow
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.2.1
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1
android.accept_sdk_license = True
android.sdk_path = $HOME/android-sdk
android.ndk_path = $HOME/android-sdk/ndk/25.2.9519653
android.sdk_manager_path = $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager
android.api = 33
android.minapi = 21
android.ndk_version = 25.2.9519653
android.skip_update = True
p4a.branch = develop
p4a.cmake = $HOME/android-sdk/cmake/3.22.1/bin/cmake
EOF

      - name: Build APK
        run: |
          export FREETYPE_INCLUDE_DIR=/usr/include/freetype2
          export FREETYPE_LIBRARY=/usr/lib/x86_64-linux-gnu/libfreetype.so
          
          buildozer android clean
          buildozer -v android debug 2>&1 | tee build.log
          
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== BUILD FAILED ==="
            tail -n 100 build.log
            echo "=== ERROR SUMMARY ==="
            grep -i "error\|fail\|exception" build.log | sort | uniq -c | sort -nr
            exit 1
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
          retention-days: 7

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
          retention-days: 7
